### ISSUE TITLE
can't save ip and port gateway

### ISSUE THREAD

**Issue by pilip87** [igdr/node-red-contrib-xiaomi-smart-devices#11]
Adding the gateway config I can set name and password (key), but adding ip address and port, after click "update" if i come back to node those fields ar cleared.
Of course I'm not receiving any data from gateway node

**Comment by igdr** [comment]
fixed: node-red-contrib-xiaomi-smart-devices@1.0.15

**Comment by BoMatt** [comment]
I have the same problem and I am on the latest version, 1.0.15. I also updated Node Red to the latest version but the issue remains (I have removed the key from the screenshot).
![image](https://user-images.githubusercontent.com/10884110/56729239-04af7700-6755-11e9-935a-3163f75cdb9e.png)

**Comment by pilip87** [comment]
I confirm issue persist in last version
