### ISSUE TITLE
Can't save Address and Port on Gateway on the latest version, 1.0.15

### ISSUE THREAD

**Issue by pilip87** [igdr/node-red-contrib-xiaomi-smart-devices#12]
I have the same problem and I am on the latest version, 1.0.15. I also updated Node Red to the latest version but the issue remains (I have removed the key from the screenshot).
![image](https://user-images.githubusercontent.com/10884110/56729239-04af7700-6755-11e9-935a-3163f75cdb9e.png)

_Originally posted by @BoMatt in https://github.com/igdr/node-red-contrib-xiaomi-smart-devices/issues/11#issuecomment-486616357_

**Comment by igdr** [comment]
I fixed it v1.0.16, could you check it up?

**Comment by pilip87** [comment]
Don't understand why, but I still see only versione 1.0.15 available in palette manager

**Comment by igdr** [comment]
Could you check it up now, it was some delay on the Node-Red side, now should be ok.

**Comment by BoMatt** [comment]
Now I can save address and port and add the devices but then Node-Red crashes.

> Error: addMembership EINVAL
>     at Socket.addMembership (dgram.js:639:11)
>     at Socket.XiaomiGatewayNode.socket.on (/home/redacted/.node-red/node_modules/node-red-contrib-xiaomi-smart-devices/devices/gateway/gateway.js:88:18)
>     at Socket.emit (events.js:197:13)
>     at startListening (dgram.js:134:10)
>     at state.handle.lookup (dgram.js:307:7)
>     at processTicksAndRejections (internal/process/next_tick.js:76:17)

**Comment by igdr** [comment]
What address and port did you set as parameters?

**Comment by BoMatt** [comment]
Address is the Xiaomi Gateway Local IP and port 9898

**Comment by igdr** [comment]
224.0.0.50?

**Comment by BoMatt** [comment]
192.168.178.34

**Comment by igdr** [comment]
You should set 224.0.0.50 or leave the address field empty. 

The error occurs when the gateway node cannot connect to the gateway (192.168.178.34), I will fix this error and display the correct error message.

**Comment by igdr** [comment]
fixed, v1.0.16

**Comment by beccsjb** [comment]
If we dont put in an IP address how does the gateway node know where to look for the hub?

**Comment by BoMatt** [comment]
> You should set 224.0.0.50 or leave the address field empty.
> 
> The error occurs when the gateway node cannot connect to the gateway (192.168.178.34), I will fix this error and display the correct error message.

Thanks, it's working now!

**Comment by igdr** [comment]
@beccsjb by default 224.0.0.50 is set as IP address and 9898 as a port
